trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - release/*
  paths:
    exclude:
      - README.md
      - docs/

variables:
  build: $(Build.BuildId)
  jobuuid: $(Build.BuildId)$(Agent.Id)
  GOROOT: '/usr/local/go1.12' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  ref: $(Build.SourceBranch)
  branch: $(Build.SourceBranchName)
  controller_image: 'gcr.io/focal-freedom-236620/controller:latest'
  version:
  vm_count: 3
  vm_1:
  vm_2:
  vm_3:

stages:
- stage: Build
  jobs:
  - job: Iofogctl
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - template: templates/prebuild-steps.yaml
    - template: templates/version-steps.yaml
    - script: |
        . version && export MAJOR && export MINOR && export PATCH && export SUFFIX
        make build
      workingDirectory: '$(modulePath)'
      displayName: 'Build Linux version'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(modulePath)/bin'
        artifactName: iofogctl-linux
    - script: |
        . version && export MAJOR && export MINOR && export PATCH && export SUFFIX
        GOOS=darwin make build
      workingDirectory: '$(modulePath)'
      displayName: 'Build OSX Binary'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(modulePath)/bin'
        artifactName: iofogctl-osx
    
- stage: Test
  jobs:
  - job: Vanilla
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - template: templates/workdir-steps.yaml
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: iofogctl-linux
        downloadPath: $(System.DefaultWorkingDirectory)
    - script: |
        sudo cp $(System.DefaultWorkingDirectory)/iofogctl-linux/iofogctl /usr/local/bin/
        sudo chmod 0755 /usr/local/bin/iofogctl
    - template: templates/postinstall-steps.yaml
    - template: templates/ssh-steps.yaml
    - template: templates/functional-init-vm-steps.yaml
    - template: templates/functional-configure.yaml
    - script: |
        for IDX in $(seq 1 $(vm_count)); do
          gcloud compute ssh iofogctl-ci-$(jobuuid)-$IDX --zone $(gcp.vm.zone) -- ls /
        done
      displayName: 'Wait for VM SSH access'
    - script: |
        set -o pipefail
        test/run.bash functional-vanilla | tee test/conf/results-functional-vanilla.tap
      workingDirectory: '$(modulePath)'
      displayName: 'Run Functional Tests'
    - script: |
        tap-junit -i test/conf/results-functional-vanilla.tap -o test/conf -s Vanilla -n results-functional-vanilla.xml
      workingDirectory: '$(modulePath)'
      displayName: 'Convert test output from TAP to JUnit'
      condition: succeededOrFailed()
    - template: templates/functional-post-test.yaml
    - template: templates/functional-clean-vm.yaml
  - job: Local
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: DownloadSecureFile@1
      displayName: 'Download secure file'
      inputs:
        secureFile: 'azure-gcp.json'
    - bash: |
        CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
        echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install google-cloud-sdk
        gcloud --quiet auth activate-service-account --key-file=$(Agent.TempDirectory)/azure-gcp.json
        gcloud --quiet config set project $(gcp.project.name)
        gcloud --quiet container clusters get-credentials $(gcp.cluster.name) --region $(gcp.cluster.region)
        gcloud --quiet auth configure-docker
      displayName: 'set up gcloud'
    - script: |
        docker pull $(controller_image)
      displayName: 'Pull latest Controller docker image'
    - template: templates/workdir-steps.yaml
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: iofogctl-linux
        downloadPath: $(System.DefaultWorkingDirectory)
    - script: |
        sudo cp $(System.DefaultWorkingDirectory)/iofogctl-linux/iofogctl /usr/local/bin/
        sudo chmod 0755 /usr/local/bin/iofogctl
    - template: templates/postinstall-steps.yaml
    - template: templates/functional-configure.yaml
    - script: |
        set -o pipefail
        test/run.bash functional-local | tee test/conf/results-functional-local.tap
      workingDirectory: '$(modulePath)'
      displayName: 'Run Functional Tests'
    - script: |
        tap-junit -i test/conf/results-functional-local.tap -o test/conf -s Local -n results-functional-local.xml
      workingDirectory: '$(modulePath)'
      displayName: 'Convert test output from TAP to JUnit'
      condition: succeededOrFailed()
    - template: templates/functional-post-test.yaml
    - script: |
        docker system prune -af
      workingDirectory: '$(modulePath)'
      condition: always()
      displayName: 'Clean local docker'
  - job: K8s
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - template: templates/workdir-steps.yaml
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: iofogctl-linux
        downloadPath: $(System.DefaultWorkingDirectory)
    - script: |
        sudo cp $(System.DefaultWorkingDirectory)/iofogctl-linux/iofogctl /usr/local/bin/
        sudo chmod 0755 /usr/local/bin/iofogctl
    - template: templates/postinstall-steps.yaml
    - template: templates/ssh-steps.yaml
    - script: echo "##vso[task.setvariable variable=vm_count]2"
    - template: templates/functional-init-vm-steps.yaml
    - template: templates/functional-configure.yaml
    - script: |
        set -o pipefail
        test/run.bash functional-k8s | tee test/conf/results-functional-k8s.tap
      workingDirectory: '$(modulePath)'
      displayName: 'Run Functional Tests'
    - script: |
        tap-junit -i test/conf/results-functional-k8s.tap -o test/conf -s K8s -n results-functional-k8s.xml
      workingDirectory: '$(modulePath)'
      displayName: 'Convert test output from TAP to JUnit'
      condition: succeededOrFailed()
    - script: |
          test/clean.bash $(jobuuid)
      workingDirectory: '$(modulePath)'
      displayName: 'Clean K8s Cluster'
      condition: always()
    - template: templates/functional-post-test.yaml
    - template: templates/functional-clean-vm.yaml
  - job: HA
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - template: templates/workdir-steps.yaml
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: iofogctl-linux
        downloadPath: $(System.DefaultWorkingDirectory)
    - script: |
        sudo cp $(System.DefaultWorkingDirectory)/iofogctl-linux/iofogctl /usr/local/bin/
        sudo chmod 0755 /usr/local/bin/iofogctl
    - template: templates/postinstall-steps.yaml
    - template: templates/ssh-steps.yaml
    - script: echo "##vso[task.setvariable variable=vm_count]2"
    - template: templates/functional-init-vm-steps.yaml
    - script: |
        sed -i "s|DB_PROVIDER=.*|DB_PROVIDER=\"postgres\"|g" test/env.sh
        sed -i "s|DB_USER=.*|DB_USER=\"$(db.user)\"|g" test/env.sh
        sed -i "s|DB_HOST=.*|DB_HOST=\"postgres-postgresql.postgres.svc.cluster.local\"|g" test/env.sh
        sed -i "s|DB_PORT=.*|DB_PORT=5432|g" test/env.sh
        sed -i "s|DB_PW=.*|DB_PW=\"$(db.pw)\"|g" test/env.sh
        sed -i "s|DB_NAME=.*|DB_NAME=\"iofog$(jobuuid)\"|g" test/env.sh
        sed -i "s|CONTROLLER_IMAGE=.*|CONTROLLER_IMAGE=\"docker.io/edgeworx/enterprise-controller:latest\"|g" test/env.sh
      workingDirectory: '$(modulePath)'
      displayName: 'Set up Postgres on K8s cluster'
    - template: templates/functional-configure.yaml
    - script: |
        set -o pipefail
        test/run.bash functional-ha | tee test/conf/results-functional-ha.tap
      workingDirectory: '$(modulePath)'
      displayName: 'Run Functional Tests'
    - script: |
        tap-junit -i test/conf/results-functional-ha.tap -o test/conf -s HA -n results-functional-ha.xml
      workingDirectory: '$(modulePath)'
      displayName: 'Convert test output from TAP to JUnit'
      condition: succeededOrFailed()
    - script: |
          test/clean.bash $(jobuuid)
      workingDirectory: '$(modulePath)'
      displayName: 'Clean K8s Cluster'
      condition: always()
    - template: templates/functional-post-test.yaml
    - template: templates/functional-clean-vm.yaml

- stage: Publish
  condition: or(and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release/')), and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/develop')), and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/')))
  jobs:
  - job: OSX
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - template: templates/workdir-steps.yaml
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: iofogctl-osx
        downloadPath: $(System.DefaultWorkingDirectory)
    - script: |
        mkdir bin
        cp $(System.DefaultWorkingDirectory)/iofogctl-osx/iofogctl bin/
      displayName: 'Download OSX Binary'
      workingDirectory: '$(modulePath)'
    - template: templates/version-steps.yaml
    - template: templates/ssh-steps.yaml
    - script: |
        . version
        tar -zcf iofogctl.tar.gz bin/iofogctl
        checksum=$(shasum -a 256 iofogctl.tar.gz | awk '{ print $1 }')
        cp iofogctl.tar.gz $(Build.ArtifactStagingDirectory)/$(version).tar.gz
        echo $(version) > $(Build.ArtifactStagingDirectory)/version.txt
        rsync -e "ssh -o StrictHostKeyChecking=no" iofogctl.tar.gz $(ssh.downloads):/var/www/vhosts/edgeworx.io/downloads/iofogctl/dev/$(version).tar.gz
        git config --global user.email "serge@edgeworx.io"
        git config --global user.name "Serge Radinovich"
        git clone git@github.com:eclipse-iofog/homebrew-iofogctl.git
        cd homebrew-iofogctl
        brew_file=iofogctl@$MAJOR.$MINOR.rb
        if [ ! -f $brew_file ]; then
          cat ../templates/brew.tpl > $brew_file
          sed -i "s/<AT_VERSION>/$MAJOR$MINOR/g" $brew_file
          sed -i "s/<DEV_SHA256>/$checksum/g" $brew_file
          sed -i "s/<DEV_VERSION>/$(version)/g" $brew_file
        else
          sed -i "s/    sha256.*/    sha256 \"$checksum\"/g" $brew_file
          sed -i "s/    version.*/    version \"$(version)\"/g" $brew_file
          sed -i "s|http://edgeworx.io/downloads/iofogctl/dev/.*\.tar\.gz\"|http://edgeworx.io/downloads/iofogctl/dev/$(version).tar.gz\"|g" $brew_file
        fi
        git add $brew_file
        git commit -m "Publish develop version $(version)"
        git push origin master
      workingDirectory: '$(modulePath)'
      displayName: 'Build and publish OSX binary'
    - template: templates/publish-steps.yaml
  - job: Debian
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: iofogctl-linux
        downloadPath: $(System.DefaultWorkingDirectory)
    - script: |
        sudo cp $(System.DefaultWorkingDirectory)/iofogctl-linux/iofogctl /usr/local/bin/
        sudo chmod 0755 /usr/local/bin/iofogctl
    - template: templates/workdir-steps.yaml
    - template: templates/version-steps.yaml
    - template: templates/publish-deps.yaml
    - script: |
        fpm -f -s dir -t deb -n iofogctl -v $(version) /usr/local/bin/iofogctl=/usr/local/bin/
        package=$(ls | grep *.deb)
        echo $package
        cp $package $(Build.ArtifactStagingDirectory)
      displayName: 'Create Debian package'
    - script: |
        package=$(ls | grep *.deb)
        echo "package..."
        echo $package
        declare -a UBUNTU_VERS=("precise" "trusty" "utopic" "vivid" "wily" "xenial" "bionic")
        declare -a DEBIAN_VERS=("wheezy" "jessie" "stretch" "buster")
        for ubu in "${UBUNTU_VERS[@]}"
        do
            package_cloud yank iofog/iofogctl-snapshots/ubuntu/${ubu} $package --config=$(Agent.TempDirectory)/package_cloud || true
            package_cloud push iofog/iofogctl-snapshots/ubuntu/${ubu} $package --config=$(Agent.TempDirectory)/package_cloud
        done
        for deb in "${DEBIAN_VERS[@]}"
        do
            package_cloud yank iofog/iofogctl-snapshots/debian/${deb} $package --config=$(Agent.TempDirectory)/package_cloud || true
            package_cloud push iofog/iofogctl-snapshots/debian/${deb} $package --config=$(Agent.TempDirectory)/package_cloud
            package_cloud yank iofog/iofogctl-snapshots/raspbian/${deb} $package --config=$(Agent.TempDirectory)/package_cloud || true
            package_cloud push iofog/iofogctl-snapshots/raspbian/${deb} $package --config=$(Agent.TempDirectory)/package_cloud
        done
      displayName: 'Publish deb to package-cloud'
    - template: templates/publish-steps.yaml
  - job: RPM
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: iofogctl-linux
        downloadPath: $(System.DefaultWorkingDirectory)
    - script: sudo cp $(System.DefaultWorkingDirectory)/iofogctl-linux/iofogctl /usr/local/bin/
    - template: templates/workdir-steps.yaml
    - template: templates/version-steps.yaml
    - template: templates/publish-deps.yaml
    - script: |
        fpm -f -s dir -t rpm -n iofogctl -v $(version) /usr/local/bin/iofogctl=/usr/local/bin/
        package=$(ls | grep *.rpm)
        echo $package
        cp $package $(Build.ArtifactStagingDirectory)
      displayName: 'Create RPM package'
    - script: |
        package=$(ls | grep *.rpm)
        echo "package..."
        echo $package
        declare -a FEDORA_VERS=("22" "23" "24")
        declare -a REDHAT_VERS=("6" "7")
        for fed in ${FEDORA_VERS[@]}
        do
            package_cloud yank iofog/iofogctl-snapshots/fedora/${fed} $package --config=$(Agent.TempDirectory)/package_cloud || true
            package_cloud push iofog/iofogctl-snapshots/fedora/${fed} $package --config=$(Agent.TempDirectory)/package_cloud
        done
        for red in ${REDHAT_VERS[@]}
        do
            package_cloud yank iofog/iofogctl-snapshots/el/${red} $package --config=$(Agent.TempDirectory)/package_cloud || true
            package_cloud push iofog/iofogctl-snapshots/el/${red} $package --config=$(Agent.TempDirectory)/package_cloud
        done
      displayName: 'Publish RPM to package-cloud'
    - template: templates/publish-steps.yaml