# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.8"

[[override]]
  name = "github.com/eclipse-iofog/iofog-operator"
  branch = "develop"

[[constraint]]
  name = "github.com/eclipse-iofog/iofog-go-sdk"
  branch = "develop"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/client-go"
  version = "v11.0.0"

[[override]]
  name = "k8s.io/api"
  # revision for tag "kubernetes-1.12.3"
  revision = "b503174bad5991eb66f18247f52e41c3258f6348"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  # revision for tag "kubernetes-1.12.3"
  revision = "0cd23ebeb6882bd1cdc2cb15fc7b2d72e8a86a5b"

[[override]]
  name = "k8s.io/apimachinery"
  # revision for tag "kubernetes-1.12.3"
  revision = "eddba98df674a16931d2d4ba75edc3a389bf633a"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.12.3"
  revision = "d082d5923d3cc0bfbb066ee5fbdea3d0ca79acf8"

[[override]]
  name = "github.com/docker/docker"
  source = "https://github.com/docker/engine"
  version = "19.03.0"

[[constraint]]
  name = "github.com/GeertJohan/go.rice"
  version = "v1.0.0"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"
