steps:
- script: |
    NS=$(jobuuid)
    sed -i "s|NAMESPACE=.*|NAMESPACE=\"$NS\"|g" test/env.sh
    sed -i "s|PACKAGE_CLOUD_TOKEN=.*|PACKAGE_CLOUD_TOKEN=\"$(pkg.token)\"|g" test/env.sh
    cp test/env.sh test/conf
  displayName: 'Configure Tests'
- script: |
    git clone https://github.com/bats-core/bats-core.git && cd bats-core && git checkout tags/v1.1.0 && sudo ./install.sh /usr/local
    # Use of sudo is recommended here: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=azure-devops#install-tools-on-your-build-agent
    sudo npm i -g tap-junit
  displayName: 'Bootstrap for Tests'
- script: |
    test/run.bash smoke
  displayName: 'Run Smoke Tests'
